spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: vfWxy33zDGmZzxJ
    listener:
#      direct:
#        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual